
server:
  port: 8080


spring:
  cloud:
    azure:
      appconfiguration:
        name: abc
        cache-expiration: 60000
        stores:
          - connection-string: Endpoint=https://template-trial-app-config-new.azconfig.io;Id=oUCt-l0-s0:cZhELXPBEWoetBayclrL;Secret=caaQCmJK3NObmy6uoVnVrROJboQOOeyjGbDzr/LSrjo=
# TODO: Put a breakpoint on line 120 of com.microsoft.azure.spring.cloud.config.AppConfigurationProperties
# to put the config above on beans startup:
#ConfigStore configStore = new ConfigStore();
#configStore.setConnectionString("Endpoint=https://template-trial-app-config-new.azconfig.io;Id=oUCt-l0-s0:cZhELXPBEWoetBayclrL;Secret=caaQCmJK3NObmy6uoVnVrROJboQOOeyjGbDzr/LSrjo=");
#this.stores = Collections.singletonList(configStore);
#this.cacheExpiration = Duration.ofMinutes(1L);

  datasource:
    driver-class-name: org.postgresql.Driver
    username: teste@template-trial-postgres.postgres.database.azure.com
    password: y0u5h0ldCh4ng3M3
    url: jdbc:postgresql://template-trial-postgres.postgres.database.azure.com:5432/template-postgres