
server:
  port: 8080

spring:
  datasource:
    driver-class-name: org.postgresql.Driver
    username: teste@template-trial-postgres.postgres.database.azure.com
    password: y0u5h0ldCh4ng3M3
    url: jdbc:postgresql://template-trial-postgres.postgres.database.azure.com:5432/template-postgres