
server:
  port: 8080


spring:
  cloud:
    azure:
      appconfiguration:
        cache-expiration: 30000
        stores:
          - connection-string: ${spring.cloud.azure.appconfiguration.stores[0].connection-string}
#Add the Environment variable when bootRun: spring.cloud.azure.appconfiguration.stores[0].connection-string=Endpoint=https://template-trial-app-config-new.azconfig.io\;Id=oUCt-l0-s0:cZhELXPBEWoetBayclrL\;Secret=caaQCmJK3NObmy6uoVnVrROJboQOOeyjGbDzr/LSrjo=

  datasource:
    driver-class-name: org.postgresql.Driver
    username: teste@template-trial-postgres.postgres.database.azure.com
    password: y0u5h0ldCh4ng3M3
    url: jdbc:postgresql://template-trial-postgres.postgres.database.azure.com:5432/template-postgres